// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aolkrquuopmsdctgxlyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFvbGtycXV1b3Btc2RjdGd4bHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTY0MDIsImV4cCI6MjA2NDY5MjQwMn0._xR9RK__p0xLwMcRUcziONBqMkVZRDGkTnAYrMmT-9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);